// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: grpcProto.proto

package grpcProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Time                []string               `protobuf:"bytes,1,rep,name=time,proto3" json:"time,omitempty"`
	ComponentName       []string               `protobuf:"bytes,2,rep,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	EventType           []string               `protobuf:"bytes,3,rep,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	RelevantIdentifiers []string               `protobuf:"bytes,4,rep,name=relevant_identifiers,json=relevantIdentifiers,proto3" json:"relevant_identifiers,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_grpcProto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_grpcProto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_grpcProto_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetTime() []string {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Message) GetComponentName() []string {
	if x != nil {
		return x.ComponentName
	}
	return nil
}

func (x *Message) GetEventType() []string {
	if x != nil {
		return x.EventType
	}
	return nil
}

func (x *Message) GetRelevantIdentifiers() []string {
	if x != nil {
		return x.RelevantIdentifiers
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpcProto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpcProto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpcProto_proto_rawDescGZIP(), []int{1}
}

var File_grpcProto_proto protoreflect.FileDescriptor

const file_grpcProto_proto_rawDesc = "" +
	"\n" +
	"\x0fgrpcProto.proto\"\x96\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04time\x18\x01 \x03(\tR\x04time\x12%\n" +
	"\x0ecomponent_name\x18\x02 \x03(\tR\rcomponentName\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x03(\tR\teventType\x121\n" +
	"\x14relevant_identifiers\x18\x04 \x03(\tR\x13relevantIdentifiers\"\a\n" +
	"\x05Empty2S\n" +
	"\vTimeService\x12!\n" +
	"\vGetMessages\x12\x06.Empty\x1a\b.Message\"\x00\x12!\n" +
	"\vSendMessage\x12\b.Message\x1a\x06.Empty\"\x00B\x19Z\x17handin-3/grpc/grpcProtob\x06proto3"

var (
	file_grpcProto_proto_rawDescOnce sync.Once
	file_grpcProto_proto_rawDescData []byte
)

func file_grpcProto_proto_rawDescGZIP() []byte {
	file_grpcProto_proto_rawDescOnce.Do(func() {
		file_grpcProto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcProto_proto_rawDesc), len(file_grpcProto_proto_rawDesc)))
	})
	return file_grpcProto_proto_rawDescData
}

var file_grpcProto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcProto_proto_goTypes = []any{
	(*Message)(nil), // 0: Message
	(*Empty)(nil),   // 1: Empty
}
var file_grpcProto_proto_depIdxs = []int32{
	1, // 0: TimeService.GetMessages:input_type -> Empty
	0, // 1: TimeService.SendMessage:input_type -> Message
	0, // 2: TimeService.GetMessages:output_type -> Message
	1, // 3: TimeService.SendMessage:output_type -> Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcProto_proto_init() }
func file_grpcProto_proto_init() {
	if File_grpcProto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcProto_proto_rawDesc), len(file_grpcProto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcProto_proto_goTypes,
		DependencyIndexes: file_grpcProto_proto_depIdxs,
		MessageInfos:      file_grpcProto_proto_msgTypes,
	}.Build()
	File_grpcProto_proto = out.File
	file_grpcProto_proto_goTypes = nil
	file_grpcProto_proto_depIdxs = nil
}
